    
    <!-- Define la codificación de caracteres -->
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <!-- Define el autor del documento -->
    <meta name="author" content="Francisco Javier Gómez García" />
    <!-- Define el programa con el que se ha generado el documento -->
    <meta name="generator" content="NetBeans 19.0" />
    <!-- Define el copyright del documento -->
    <meta name="copyright" content="DWES" />
    <!-- Define el comportamiento de los buscadores -->
    <meta name="robots" content="index, follow" />
    <!-- Define las palabras claves del contenido del documento -->
    <meta name="keywords" content="Tienda" />
    <!-- Define una breve descripción del sitio -->
    <meta name="description" content="Tienda de productos informaticos" />
